MoviePlannerSystem/config/routes.rb
MoviePlannerSystem::Application.routes.draw do
  resources :user_infos

  resources :user_movie_theatres

  resources :movie_theatres

  resources :theatres

  resources :user_movies

  resources :movies

  root :to=>"home#index"

  devise_for :users

end

MoviePlannerSystem/app/models/movie_theatre.rb
class MovieTheatre < ActiveRecord::Base
  belongs_to :movie
  belongs_to :theatre
  # attr_accessible :title, :body
end

MoviePlannerSystem/app/controllers/movie_theatres_controller.rb
class MovieTheatresController < ApplicationController
  # GET /movie_theatres
  # GET /movie_theatres.json
  def index
    @movie_theatres = MovieTheatre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movie_theatres }
    end
  end

  # GET /movie_theatres/1
  # GET /movie_theatres/1.json
  def show
    @movie_theatre = MovieTheatre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie_theatre }
    end
  end

  # GET /movie_theatres/new
  # GET /movie_theatres/new.json
  def new
    @movie_theatre = MovieTheatre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie_theatre }
    end
  end

  # GET /movie_theatres/1/edit
  def edit
    @movie_theatre = MovieTheatre.find(params[:id])
  end

  # POST /movie_theatres
  # POST /movie_theatres.json
  def create
    @movie_theatre = MovieTheatre.new(params[:movie_theatre])

    respond_to do |format|
      if @movie_theatre.save
        format.html { redirect_to @movie_theatre, notice: 'Movie theatre was successfully created.' }
        format.json { render json: @movie_theatre, status: :created, location: @movie_theatre }
      else
        format.html { render action: "new" }
        format.json { render json: @movie_theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movie_theatres/1
  # PUT /movie_theatres/1.json
  def update
    @movie_theatre = MovieTheatre.find(params[:id])

    respond_to do |format|
      if @movie_theatre.update_attributes(params[:movie_theatre])
        format.html { redirect_to @movie_theatre, notice: 'Movie theatre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie_theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_theatres/1
  # DELETE /movie_theatres/1.json
  def destroy
    @movie_theatre = MovieTheatre.find(params[:id])
    @movie_theatre.destroy

    respond_to do |format|
      format.html { redirect_to movie_theatres_url }
      format.json { head :no_content }
    end
  end
end

MoviePlannerSystem/app/helpers/movie_theatres_helper.rb
module MovieTheatresHelper
end

MoviePlannerSystem/app/views/movie_theatres/_form.html.erb
<%= form_for(@movie_theatre) do |f| %>
  <% if @movie_theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_theatre.errors.count, "error") %> prohibited this movie_theatre from being saved:</h2>

      <ul>
      <% @movie_theatre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie %><br />
    <%= f.text_field :movie %>
  </div>
  <div class="field">
    <%= f.label :theatre %><br />
    <%= f.text_field :theatre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MoviePlannerSystem/app/views/movie_theatres/edit.html.erb
<h1>Editing movie_theatre</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_theatre %> |
<%= link_to 'Back', movie_theatres_path %>

MoviePlannerSystem/app/views/movie_theatres/index.html.erb
<h1>Listing movie_theatres</h1>

<table>
  <tr>
    <th>Movie</th>
    <th>Theatre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movie_theatres.each do |movie_theatre| %>
  <tr>
    <td><%= movie_theatre.movie %></td>
    <td><%= movie_theatre.theatre %></td>
    <td><%= link_to 'Show', movie_theatre %></td>
    <td><%= link_to 'Edit', edit_movie_theatre_path(movie_theatre) %></td>
    <td><%= link_to 'Destroy', movie_theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie theatre', new_movie_theatre_path %>

MoviePlannerSystem/app/views/movie_theatres/new.html.erb
<h1>New movie_theatre</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_theatres_path %>

MoviePlannerSystem/app/views/movie_theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie:</b>
  <%= @movie_theatre.movie %>
</p>

<p>
  <b>Theatre:</b>
  <%= @movie_theatre.theatre %>
</p>


<%= link_to 'Edit', edit_movie_theatre_path(@movie_theatre) %> |
<%= link_to 'Back', movie_theatres_path %>