MoviePlannerSystem/config/routes.rb
MoviePlannerSystem::Application.routes.draw do
  resources :user_infos

  resources :user_movie_theatres

  resources :movie_theatres

  resources :theatres

  resources :user_movies

  resources :movies

  root :to=>"home#index"

  devise_for :users

end

MoviePlannerSystem/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

MoviePlannerSystem/app/helpers/movies_helper.rb
module MoviesHelper
end

MoviePlannerSystem/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
   <div class="field">
   	 <%= f.label :date %><br />
	  <div id="datetimepicker2" class="input-append">
    	<input data-format="MM/dd/yyyy HH:mm:ss PP" type="text"></input>
	    <span class="add-on">
	      <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
	    </span>
	  </div>
	</div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :booked_status %><br />
    <%= f.text_field :booked_status %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MoviePlannerSystem/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

MoviePlannerSystem/app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>Booked status</th>
    <th>Language</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.name %></td>
    <td><%= movie.date %></td>
    <td><%= movie.location %></td>
    <td><%= movie.booked_status %></td>
    <td><%= movie.language %></td>
    <td><%= movie.link %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

MoviePlannerSystem/app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

MoviePlannerSystem/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<p>
  <b>Date:</b>
  <%= @movie.date %>
</p>

<p>
  <b>Location:</b>
  <%= @movie.location %>
</p>

<p>
  <b>Booked status:</b>
  <%= @movie.booked_status %>
</p>

<p>
  <b>Language:</b>
  <%= @movie.language %>
</p>

<p>
  <b>Link:</b>
  <%= @movie.link %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>