MoviePlannerSystem/config/routes.rb
MoviePlannerSystem::Application.routes.draw do
  resources :user_infos

  resources :user_movie_theatres

  resources :movie_theatres

  resources :theatres

  resources :user_movies

  resources :movies

  root :to=>"home#index"

  devise_for :users

end

MoviePlannerSystem/app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :Bank_Details, :location, :name, :phone, :preferted_genre
end

MoviePlannerSystem/app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_infos }
    end
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
    @user_info = UserInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_info }
    end
  end

  # GET /user_infos/new
  # GET /user_infos/new.json
  def new
    @user_info = UserInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_info }
    end
  end

  # GET /user_infos/1/edit
  def edit
    @user_info = UserInfo.find(params[:id])
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    @user_info = UserInfo.new(params[:user_info])

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render json: @user_info, status: :created, location: @user_info }
      else
        format.html { render action: "new" }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_infos/1
  # PUT /user_infos/1.json
  def update
    @user_info = UserInfo.find(params[:id])

    respond_to do |format|
      if @user_info.update_attributes(params[:user_info])
        format.html { redirect_to @user_info, notice: 'User info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info = UserInfo.find(params[:id])
    @user_info.destroy

    respond_to do |format|
      format.html { redirect_to user_infos_url }
      format.json { head :no_content }
    end
  end
end

MoviePlannerSystem/app/helpers/user_infos_helper.rb
module UserInfosHelper
end

MoviePlannerSystem/app/views/user_infos/_form.html.erb
<%= form_for(@user_info) do |f| %>
  <% if @user_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>

      <ul>
      <% @user_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Bank_Details %><br />
    <%= f.text_area :Bank_Details %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :preferted_genre %><br />
    <%= f.text_field :preferted_genre %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MoviePlannerSystem/app/views/user_infos/edit.html.erb
<h1>Editing user_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_info %> |
<%= link_to 'Back', user_infos_path %>

MoviePlannerSystem/app/views/user_infos/index.html.erb
<h1>Listing user_infos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bank details</th>
    <th>Phone</th>
    <th>Location</th>
    <th>Preferted genre</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_infos.each do |user_info| %>
  <tr>
    <td><%= user_info.name %></td>
    <td><%= user_info.Bank_Details %></td>
    <td><%= user_info.phone %></td>
    <td><%= user_info.location %></td>
    <td><%= user_info.preferted_genre %></td>
    <td><%= user_info.user %></td>
    <td><%= link_to 'Show', user_info %></td>
    <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
    <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User info', new_user_info_path %>

MoviePlannerSystem/app/views/user_infos/new.html.erb
<h1>New user_info</h1>

<%= render 'form' %>

<%= link_to 'Back', user_infos_path %>

MoviePlannerSystem/app/views/user_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user_info.name %>
</p>

<p>
  <b>Bank details:</b>
  <%= @user_info.Bank_Details %>
</p>

<p>
  <b>Phone:</b>
  <%= @user_info.phone %>
</p>

<p>
  <b>Location:</b>
  <%= @user_info.location %>
</p>

<p>
  <b>Preferted genre:</b>
  <%= @user_info.preferted_genre %>
</p>

<p>
  <b>User:</b>
  <%= @user_info.user %>
</p>


<%= link_to 'Edit', edit_user_info_path(@user_info) %> |
<%= link_to 'Back', user_infos_path %>