MoviePlannerSystem/config/routes.rb
MoviePlannerSystem::Application.routes.draw do
  resources :user_infos

  resources :user_movie_theatres

  resources :movie_theatres

  resources :theatres

  resources :user_movies

  resources :movies

  root :to=>"home#index"

  devise_for :users

end

MoviePlannerSystem/app/models/theatre.rb
class Theatre < ActiveRecord::Base
  attr_accessible :theatre_name
end

MoviePlannerSystem/app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  # GET /theatres
  # GET /theatres.json
  def index
    @theatres = Theatre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @theatres }
    end
  end

  # GET /theatres/1
  # GET /theatres/1.json
  def show
    @theatre = Theatre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @theatre }
    end
  end

  # GET /theatres/new
  # GET /theatres/new.json
  def new
    @theatre = Theatre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @theatre }
    end
  end

  # GET /theatres/1/edit
  def edit
    @theatre = Theatre.find(params[:id])
  end

  # POST /theatres
  # POST /theatres.json
  def create
    @theatre = Theatre.new(params[:theatre])

    respond_to do |format|
      if @theatre.save
        format.html { redirect_to @theatre, notice: 'Theatre was successfully created.' }
        format.json { render json: @theatre, status: :created, location: @theatre }
      else
        format.html { render action: "new" }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /theatres/1
  # PUT /theatres/1.json
  def update
    @theatre = Theatre.find(params[:id])

    respond_to do |format|
      if @theatre.update_attributes(params[:theatre])
        format.html { redirect_to @theatre, notice: 'Theatre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1
  # DELETE /theatres/1.json
  def destroy
    @theatre = Theatre.find(params[:id])
    @theatre.destroy

    respond_to do |format|
      format.html { redirect_to theatres_url }
      format.json { head :no_content }
    end
  end
end

MoviePlannerSystem/app/helpers/theatres_helper.rb
module TheatresHelper
end

MoviePlannerSystem/app/views/theatres/_form.html.erb
<%= form_for(@theatre) do |f| %>
  <% if @theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theatre.errors.count, "error") %> prohibited this theatre from being saved:</h2>

      <ul>
      <% @theatre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :theatre_name %><br />
    <%= f.text_field :theatre_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MoviePlannerSystem/app/views/theatres/edit.html.erb
<h1>Editing theatre</h1>

<%= render 'form' %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

MoviePlannerSystem/app/views/theatres/index.html.erb
<h1>Listing theatres</h1>

<table>
  <tr>
    <th>Theatre name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @theatres.each do |theatre| %>
  <tr>
    <td><%= theatre.theatre_name %></td>
    <td><%= link_to 'Show', theatre %></td>
    <td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
    <td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Theatre', new_theatre_path %>

MoviePlannerSystem/app/views/theatres/new.html.erb
<h1>New theatre</h1>

<%= render 'form' %>

<%= link_to 'Back', theatres_path %>

MoviePlannerSystem/app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Theatre name:</b>
  <%= @theatre.theatre_name %>
</p>


<%= link_to 'Edit', edit_theatre_path(@theatre) %> |
<%= link_to 'Back', theatres_path %>